//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTime_Vol_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class MovieWatchlist
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string MovieID { get; set; }
        public string Title { get; set; }
        public string Overview { get; set; }
        public string Release_date { get; set; }
        public string Popularity { get; set; }
        public string Poster_path { get; set; }
        [DisplayName("Watchlist name")]
        public string WatchlistName { get; set; }
    }
}
